### ISSUE TITLE
NoSuchFieldException when run with JUnit 2.12

### ISSUE THREAD

**Issue by jholleran** [lucaspouzac/contiperf#9]
Hi,

We are using Contiperf in a project. While updating the JUnit version from junit-4.10 to junit-4.12 our tests fail with the following exception: 

java.lang.RuntimeException: java.lang.NoSuchFieldException: fNext
	at org.databene.contiperf.junit.ContiPerfRule.apply(ContiPerfRule.java:176)
	at org.junit.runners.BlockJUnit4ClassRunner.withMethodRules(BlockJUnit4ClassRunner.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:355)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NoSuchFieldException: fNext
	at java.lang.Class.getDeclaredField(Class.java:1953)
	at org.databene.contiperf.junit.ContiPerfRule.apply(ContiPerfRule.java:171)
	... 17 more

It looks like it is throwing this exception because the private field (Statement) name in RunBefores has changed from "fNext" to "next" in JUnit 2.12.

Can this issue be fixed?

**Comment by TommyYehCool** [comment]
Does this version can download from maven repository ?
